apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-pod
  template:
    metadata:
      labels:
        app: order-pod
    spec:
      containers:
      - name: order-container
        image: 262583979852.dkr.ecr.us-east-1.amazonaws.com/order-service-mena:latest
        ports:
        - containerPort: 8100
        imagePullPolicy: Always
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: qa
        - name: TZ
          value: America/Mexico_City
        - name: ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: database
              key: ACCESS_KEY
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: database
              key: SECRET_KEY
        - name: RDS_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: database
              key: RDS_ENDPOINT
        - name: RDS_USER
          valueFrom:
            secretKeyRef:
              name: database
              key: RDS_USER
        - name: RDS_PASS
          valueFrom:
            secretKeyRef:
              name: database
              key: RDS_PASS
        - name: ENDPOINT_PAYMENT_ORDER_SQS
          valueFrom:
            secretKeyRef:
              name: database
              key: ENDPOINT_PAYMENT_ORDER_SQS
        - name: ENDPOINT_PAYMENT_KITCHEN_SQS
          valueFrom:
            secretKeyRef:
              name: database
              key: ENDPOINT_PAYMENT_KITCHEN_SQS
        - name: ENDPOINT_ORDER_SQS
          valueFrom:
            secretKeyRef:
              name: database
              key: ENDPOINT_ORDER_SQS
        - name: ENDPOINT_TICKETS_SQS
          valueFrom:
            secretKeyRef:
              name: database
              key: ENDPOINT_TICKETS_SQS
        - name: PAYMENT_ORDER_SQS
          valueFrom:
            secretKeyRef:
              name: database
              key: PAYMENT_ORDER_SQS
        - name: PAYMENT_KITCHEN_SQS
          valueFrom:
            secretKeyRef:
              name: database
              key: PAYMENT_KITCHEN_SQS
        - name: TICKETS_SQS
          valueFrom:
            secretKeyRef:
              name: database
              key: TICKETS_SQS
        - name: ORDER_SQS
          valueFrom:
            secretKeyRef:
              name: database
              key: ORDER_SQS
---
apiVersion: v1
kind: Service
metadata:
  name: order-svc
spec:
  selector:
    app: order-pod
  ports:
  - port: 8100
    protocol: TCP
    targetPort: 8100
  type: LoadBalancer