apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-depp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-pod
  template:
    metadata:
      labels:
        app: payment-pod
    spec:
      containers:
      - name: payment-container
        image: 262583979852.dkr.ecr.us-east-1.amazonaws.com/payment-service:latest
        ports:
        - containerPort: 8300
        imagePullPolicy: Always
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: qa
        - name: TZ
          value: America/Mexico_City
        - name: ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: database
              key: ACCESS_KEY
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: database
              key: SECRET_KEY
        - name: RDS_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: database
              key: RDS_ENDPOINT
        - name: RDS_USER
          valueFrom:
            secretKeyRef:
              name: database
              key: RDS_USER
        - name: RDS_PASS
          valueFrom:
            secretKeyRef:
              name: database
              key: RDS_PASS
        - name: ENDPOINT_PAYMENT_SQS
          valueFrom:
            secretKeyRef:
              name: database
              key: ENDPOINT_PAYMENT_SQS
        - name: ENDPOINT_ORDER_SQS
          valueFrom:
            secretKeyRef:
              name: database
              key: ENDPOINT_ORDER_SQS
        - name: ENDPOINT_TICKETS_SQS
          valueFrom:
            secretKeyRef:
              name: database
              key: ENDPOINT_TICKETS_SQS
---
apiVersion: v1
kind: Service
metadata:
  name: payment-svc
spec:
  selector:
    app: payment-pod
  ports:
  - port: 8300
    protocol: TCP
    targetPort: 8300
  type: LoadBalancer